version: "3"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-rtmpserver
    environment: 
      MTX_PROTOCOLS: tcp
      MTX_WEBRTCADDITIONALHOSTS: "127.0.0.1"
      RTSP_API: yes
    ports:
      - "9997:9997"
      - "9996:9996"
      - "8554:8554"  # RTSP (default port)
      - "8000:8000"
      - "8001:8001"
      - "1236:1236"
      - "1935:1935"  # RTMP (default port)
      - "8888:8888"  # HLS (default port)
      - "8889:8889"  # WebRTC (default port)
      - "8890:8890/udp"  # Additional WebRTC port (UDP)
      - "8189:8189/udp"  # Additional protocol port (UDP, adjust as needed)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro  # Mount your local mediamtx.yml file

# volumes:
#   live_server_data:

  # rclone:
  #   image: rclone/rclone:latest
  #   command: config
    # volumes:
    #   - /path/to/host/config:/config/rclone
    #   - /path/to/host/data:/data
